basePath: /api
definitions:
  controllers.requestOtpParams:
    properties:
      phone:
        type: string
    type: object
  controllers.verifOtpParams:
    properties:
      otp:
        type: string
      phone:
        type: string
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      displayName:
        type: string
      id:
        type: string
      phone:
        type: string
      updatedAt:
        type: string
      userAddress:
        items:
          $ref: '#/definitions/models.UserAddress'
        type: array
    required:
    - phone
    type: object
  models.UserAddress:
    properties:
      address:
        type: string
      city:
        type: string
      createdAt:
        type: string
      detai:
        type: string
      id:
        type: string
      phone:
        type: string
      postalCode:
        type: string
      recipient:
        type: string
      title:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: novandaahsan1@gmail.com
    name: API Support
    url: https://github.com/novanda1
  description: The Sayurmax REST API built with GO
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: SayurGO API
  version: 0.0.1
paths:
  /api/verif:
    post:
      consumes:
      - application/json
      description: verif Authorization that return JWT code.
      parameters:
      - description: Your Phone Number
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controllers.verifOtpParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: get JWT code
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Request Authorization that return OTP code.
      parameters:
      - description: Your Phone Number
        in: body
        name: phone
        required: true
        schema:
          $ref: '#/definitions/controllers.requestOtpParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.verifOtpParams'
      summary: get OTP code
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
x-extension-openapi:
  example: value on a json format
