definitions:
  controllers.requestOtpParams:
    properties:
      phone:
        type: string
    type: object
  controllers.verifOtpParams:
    properties:
      otp:
        type: string
      phone:
        type: string
    type: object
  controllers.verifOtpResponse:
    properties:
      success:
        type: boolean
      token:
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  models.Product:
    properties:
      categories:
        items:
          type: string
        type: array
      createdAt:
        type: string
      discountPrice:
        type: integer
      id:
        type: string
      imageUrl:
        type: string
      information:
        type: string
      nutrition:
        type: string
      price:
        type: integer
      title:
        type: string
      unitType:
        type: string
      updatedAt:
        type: string
    required:
    - categories
    - imageUrl
    - information
    - nutrition
    - price
    - title
    - unitType
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      displayName:
        type: string
      id:
        type: string
      phone:
        type: string
      updatedAt:
        type: string
      userAddress:
        items:
          $ref: '#/definitions/models.UserAddress'
        type: array
    required:
    - phone
    type: object
  models.UserAddress:
    properties:
      address:
        type: string
      city:
        type: string
      createdAt:
        type: string
      detai:
        type: string
      id:
        type: string
      phone:
        type: string
      postalCode:
        type: string
      recipient:
        type: string
      title:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: novandaahsan1@gmail.com
    name: API Support
    url: https://github.com/novanda1
  description: The Sayurmax REST API built with GO
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: SayurGO API
  version: 0.0.1
paths:
  /admin/products:
    post:
      consumes:
      - application/json
      description: Create a brand new product.
      parameters:
      - description: Product
        in: body
        name: body
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
      summary: 'Admin: Create Product'
      tags:
      - Product
  /admin/products/{id}:
    delete:
      consumes:
      - application/json
      description: Delete specific product.
      parameters:
      - description: Product ID
        in: path
        name: id
        type: integer
      produces:
      - application/json
      summary: 'Admin: Delete Product'
      tags:
      - Product
    put:
      consumes:
      - application/json
      description: Update some data in specific product.
      parameters:
      - description: Product
        in: body
        name: body
        schema:
          $ref: '#/definitions/models.Product'
      - description: Product ID
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
      summary: 'Admin: Update Product'
      tags:
      - Product
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Request Authorization that return OTP code.
      parameters:
      - description: Your Phone Number
        in: body
        name: phone
        required: true
        schema:
          $ref: '#/definitions/controllers.requestOtpParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.verifOtpParams'
      summary: Request OTP code
      tags:
      - Auth
  /api/auth/verif:
    post:
      consumes:
      - application/json
      description: Verify OTP code.
      parameters:
      - description: Your Phone Number
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controllers.verifOtpParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.verifOtpResponse'
      summary: Verify OTP code and get JWT code
      tags:
      - Auth
  /api/products:
    get:
      consumes:
      - application/json
      description: Get all product returned array of products.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
      summary: Get All Products
      tags:
      - Product
  /api/products/{id}:
    get:
      consumes:
      - application/json
      description: Get product returned products object.
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
      summary: Get Product
      tags:
      - Product
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
x-extension-openapi:
  example: value on a json format
